alexisM8/capstone_aggieaccess

README.md

This better work oe else

---

signup_page.html

I started a sign up page we could possibly begin work on. Future modifications and changes must be made.

Created an intital sign up page

---

forgot_password.html
login.html
signup_page.html

Added forgot password page and linked all pages together

forgot password page + styling

---

signup_page.html

Query for Professor schedule added to query.txt

---

signup_page.html
signup_page.php
style.css

I modified the existing signup_page.html file but it is now obsolete. A new functional signup_page.php was added that allows us to add user to the local database. A CSS file was created for general purpose.

Changes to Sign Up Page and added CSS file

---

creds.php
faculty.html
login.html
login.php
student.html

added login functionality that aligns with our database, faculty and student pages are plain just to test the login

added login.php as well as plain student and faculty pages

---

admin.html
creds.php
login.php

admin directory, change credentials to something easier in login.php

admin directory + forgot password

---

creds.php

added root to password in creds file

cred pass added

---

query.sql

Added queries for list classes based on CRN, list of courses, and list of courses based on the department

Added 3 queries

---

chair/ContactStudent.php

updated contact student page

---

student/Home.php

I've modified the student home page to display a welcome message followed by the student name. Also added the text under the message noting the student information.

Added welcome message to student home page.

---

Admin/view.php
admin.php

style changes to admin for consistency

admin styling

---

student.php
student/studentschedule.php

Added student information to the View Schedule page. Made a small change to student.php as well. There was a misspelling with "Contact Advisor" that was fixed.

Added student information to the View Schedule page.

---

Faculty/EnrollStudent.php

added the search student and department

updated EnrollStudent.php

---

Faculty/EnrollStudent.php

Sort of got some functionality to enroll the students as a faculty. Problems:  only works for ar@cameron.edu, and table is printed beforehand.

Enrolling Students as Faculty

---

Faculty/EnrollStudent.php

Fixed an issue in which the table labels would appear before hitting the submit button.

Faculty Enrollment Table Labels 

---

chair/EnrollStudent.php

Replicated the faculty student enroll page to the chair student enroll page.

Chair Student Enrollment

---

chair/ListAdvisor.php

Made chair list advisor page the same as the faculty.

Replicated faculty list advisor to chair list advisor.

---

student.php
student/studentscourseenrollemnt.php

 Centered the button:)

---

Admin/delete.php
Admin/insert.php

Changed the post “admin.php” to “?page=AdminDelete” and “signup_page.php” to “?page=AdminInsert” that was displaying incorrect pages. After that, admin delete was outputting: “Uncaught mysqli_sql_exception”. Updated query and now delete and insert page are working properly.

fixed admin insert and delete function

---

Secretary/ContactStudent.php
Secretary/ContactTeacher.php
Secretary/LisrAdvisor.php
secretary.php

Modified Secretary List Advisor, Contact Student, and Contact Teacher pages to resemble the Chair's side.

Secretary Tabs Changes

---

Admin/view.php

display office number details

---

Chair.php
chair/AddCourse.php

Page 80% Complete 
Need to make the department a drop down

Chair Add Course Page

---

Chair.php
chair/AddCourse.php
chair/AddCourse2.php

Finished the page and now it has a drop down

Finished the page

---

forgot_password.php

but needs to fix the password actually changing to "Cameron2023"

forgot_password.php is changed

---

Faculty/ListTeachingSchedule.php
Faculty/studentschedule.php
chair/ListTeachingSchedule.php
chair/studentschedule.php
student.php
student/studentschedule.php

Added building abbrv. to all pages that included a schedule.

Added Building Abbreviations to Schedule Pages

---

Chair.php
Faculty/studentschedule.php
chair/studentschedule.php
faculty.php

Added remove and print buttons to student schedule pages for various logins.

Added Remove Buttons 

---

chair/studentschedule.php

Fixed an error on the Chair side with student schedule.

Fixed Student Schedule Chair Side

---

Faculty/studentschedule.php

fixed the issue where remove button was not working on faculty side

Faculty student schedule remove button

---

forgot_password.php

forgot_password is fully functional

updates forgot password

---

Welcome.php
forgot_password.php
login.php
signup_page.css
signup_page.php
style.css

Changed the styling for login, sign up, and forgot password page. Made additional quality changes.

Credential Pages Styling

---

Chair.php
Faculty/ClassRoster.php
Faculty/ContactStudent.php
Faculty/EnrollStudent.php
Faculty/ListTeachingSchedule.php
Secretary/ContactTeacher.php
Secretary/Home.php
Secretary/ListItStudent.php
admin.php
chair/AddCourse.php
chair/AssignAdvisor.php
chair/ClassListing.php
chair/ContactTeacher.php
chair/EnrollStudent.php
chair/Home.php
chair/ListItStudent.php
chair/studentschedule.php
faculty.php
secretary.php
student.php
student/studentEnrollclasses.php
student/studentscourseenrollemnt.php

Styled and fixed grammar changes to all pages

Changes to all pages

---

student/studentscourseenrollemnt.php

There will be a confirmation message after the student presses the Copy Text button that says "Text copied"  to signify the pin was copied.

added a confirmation message of text copied after on button click

---

admin.php
faculty.php
student.php

I changed the background color to light grey on the admin, faculty, and student pages. These are the last frontend changes from me.

changed the background color for student,admin,faculty pages 
